# Generated by Django 5.1.3 on 2024-11-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='authoro',
        ),
    ]
