# Generated by Django 5.1.3 on 2024-11-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_author_post_authoro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authoro',
            new_name='author',
        ),
    ]
